name = "test-project-worker"
main = "dist/index.js"
compatibility_date = "2025-10-25"
compatibility_flags = ["nodejs_compat"]

[vars]
ENVIRONMENT = "development"

[env.production]
name = "test-project-worker-prod"
vars = { ENVIRONMENT = "production" }

[env.staging]
name = "test-project-worker-staging"
vars = { ENVIRONMENT = "staging" }

# Optional: Hyperdrive für DB-Proxy nutzen (Cloudflare)
# Siehe: https://developers.cloudflare.com/hyperdrive/
# [hyperdrive]
# bindings = [
#   { name = "HYPERDRIVE", database = "<your-hyperdrive-name>" }
# ]
