name = "fullstack-template-backend"
main = "dist/main.js"
compatibility_date = "2025-10-25"

[build]
command = "pnpm install && pnpm build && pnpm prisma generate"

[env.production]
name = "fullstack-template-backend-prod"
vars = { ENVIRONMENT = "production" }

[env.staging]
name = "fullstack-template-backend-staging"
vars = { ENVIRONMENT = "staging" }

[[rules]]
type = "ESModule"
globs = ["**/*.js"]
fallthrough = true