name = "fullstack-template-backend"
compatibility_date = "2025-10-25"

[build]
command = "pnpm install && pnpm build && pnpm prisma generate"
entry-point = "dist/main.js"

[env.production]
name = "fullstack-template-backend-prod"
vars = { ENVIRONMENT = "production" }

[env.staging]
name = "fullstack-template-backend-staging"
vars = { ENVIRONMENT = "staging" }

[[rules]]
type = "ESModule"
fallthrough = true